RNG_SEED: 54

OUTPUT_DIR: 'D:\Anomaly\MSFR\log_MSFR_AeBAD_S_'


DATASET:
  name: 'aebad_S'
  resize: 256
  imagesize: 224
  subdatasets: ["AeBAD_S"]
  domain_shift_category: "same"

TRAIN:
  enable: True
  save_model: True
  method: 'MSFR'
  dataset_path: 'D:\Datasets\AeBAD\AeBAD\'
  backbone: 'wideresnet50'

  MSFR:
    DA_low_limit: 0.7
    DA_up_limit: 1.
    layers_to_extract_from : ["layer1", "layer2", "layer3"]
    feature_compression : False
    scale_factors : (4.0, 2.0, 1.0)
    FPN_output_dim : (256, 512, 1024)
    load_pretrain_model : True
    model_chkpt : 'D:\Anomaly\MSFR\pretrain_model\mae_visualize_vit_base.pth'
    finetune_mask_ratio : 0.4
    test_mask_ratio : 0.


TRAIN_SETUPS:
  batch_size: 8  #16
  num_workers: 8
  learning_rate: 0.001
  epochs: 200
  weight_decay: 0.05
  warmup_epochs: 50

TEST:
  enable: True
  save_segmentation_images: True
  method: 'MSFR'
  dataset_path: 'D:\Datasets\AeBAD\AeBAD\'

  VISUALIZE:
    Random_sample: True

TEST_SETUPS:
  batch_size: 8 # 32