RNG_SEED: 54

OUTPUT_DIR: './log_MSFR_MVTec'


DATASET:
  name: 'mvtec'
  resize: 256
  imagesize: 224
  subdatasets: ["bottle"]
                # "cable",
                # "capsule",
                # "carpet",
                # "grid",
                # "hazelnut",
                # "leather",
                # "metal_nut",
                # "pill",
                # "screw",
                # "tile",
                # "toothbrush",
                # "transistor",
                # "wood",
                # "zipper"]

TRAIN:
  enable: True
  save_model: False
  method: 'MSFR'
  dataset_path: '/home/kucarst3-dlws/ku500944/dataset/mvtec_bottle'
  backbone: 'wideresnet50'

  MSFR:
    DA_low_limit: 0.7
    DA_up_limit: 1.
    layers_to_extract_from : ["layer1", "layer2", "layer3"]
    feature_compression : False
    scale_factors : (4.0, 2.0, 1.0)
    FPN_output_dim : (256, 512, 1024)
    load_pretrain_model : True
    model_chkpt : "/home/kucarst3-dlws/ku500944/models/MSFR/pretrain_model/mae_visualize_vit_base.pth"
    finetune_mask_ratio : 0.4
    test_mask_ratio : 0.


TRAIN_SETUPS:
  batch_size: 16
  num_workers: 8
  learning_rate: 0.001
  epochs: 2
  weight_decay: 0.05
  warmup_epochs: 50

TEST:
  enable: False
  save_segmentation_images: True
  method: 'MSFR'
  dataset_path: '/home/kucarst3-dlws/ku500944/dataset/mvtec_bottle'

  VISUALIZE:
    Random_sample: True

TEST_SETUPS:
  batch_size: 32